// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJbOvP0SR9GLWpC6Ga60l0-jyk5VB-JZA',
    appId: '1:41844358248:web:93badbda127a25439b8fdd',
    messagingSenderId: '41844358248',
    projectId: 'funli-app',
    authDomain: 'funli-app.firebaseapp.com',
    storageBucket: 'funli-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuPUvNNrRuMuNj3pPzIeXyYGbiYFRyLao',
    appId: '1:41844358248:android:ea48fd87ad627c0d9b8fdd',
    messagingSenderId: '41844358248',
    projectId: 'funli-app',
    storageBucket: 'funli-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDunAEFpdu4SxwKOZD6fqdzBpiLFKkEQnU',
    appId: '1:41844358248:ios:2c277a75e0b8d6c89b8fdd',
    messagingSenderId: '41844358248',
    projectId: 'funli-app',
    storageBucket: 'funli-app.firebasestorage.app',
    androidClientId: '41844358248-4cj99mp1bsl7nhmo63jbhsl6ha2b06c5.apps.googleusercontent.com',
    iosClientId: '41844358248-g9kdkvhpt8nqn4b7q0k732v0tpf7639h.apps.googleusercontent.com',
    iosBundleId: 'com.sherazapps.moodstream',
  );
}
